# Generated by Django 2.2.6 on 2019-11-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abiturintupost',
            options={'verbose_name': 'Абітурієнту', 'verbose_name_plural': 'Абітурієнту'},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': 'Новини', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='studentupost',
            options={'verbose_name': 'Студенту', 'verbose_name_plural': 'Студенту'},
        ),
    ]
